In [15]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [16]:
df = pd.read_csv('heart.csv')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [27]:
df.shape

(1025, 14)

In [18]:
df.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   

   ca  thal  target  
0   2     3       0  
1   0     3       0

In [19]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

In [20]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [21]:
lr.fit(X_train,y_train)

LogisticRegression()

In [22]:
lr.coef_
# fitted coef

array([[ 0.0160498 , -1.67850893,  0.78611481, -0.01720672, -0.00604616,
        -0.1941905 ,  0.48609554,  0.03471399, -0.80620443, -0.44373186,
         0.61523696, -0.76542273, -0.84736174]])

In [23]:
lr.intercept_
# model intercept

array([0.12842175])

In [24]:
y_pred = lr.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
# accuracy
print('accuracy: ', accuracy_score(y_test,y_pred))

accuracy:  0.8536585365853658


In [32]:
#confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 68,  19],
       [ 11, 107]], dtype=int64)

In [36]:
print('precision : ')
precision_score(y_test, y_pred)

precision : 


0.8492063492063492

In [37]:
print('recall : ')
recall_score(y_test, y_pred)

recall : 


0.9067796610169492

In [38]:
print('f1 score : ')
f1_score(y_test, y_pred)

f1 score : 


0.8770491803278688