In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('data\customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
49   25  Female     Good        UG        No
48   39  Female     Good        UG       Yes
21   32    Male  Average        PG        No
24   16  Female  Average        PG       Yes
14   15    Male     Poor        PG       Yes

In [4]:
df = df.iloc[:,2:] # for gender column we need a one hot coading hence not using

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
X_train

review education
4   Average        UG
44  Average        UG
9      Good        UG
13  Average    School
43     Poor        PG
38     Good    School
36     Good        UG
3      Good        PG
29  Average        UG
8   Average        UG
24  Average        PG
15     Poor        UG
35     Poor    School
40     Good    School
7      Poor    School
20  Average    School
49     Good        UG
22     Poor        PG
19     Poor        PG
12     Poor    School
0   Average    School
25     Good    School
2      Good        PG
34  Average    School
31     Poor    School
39     Poor        PG
18     Good    School
28     Poor    School
47     Good        PG
1      Poor        UG
46     Poor        PG
23     Good    School
32  Average        UG
48     Good        UG
30  Average        UG
17     Poor        UG
33     Good        PG
41     Good        PG
45     Poor        PG
16     Poor        UG

In [21]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])  # ,maintains the sequence good has high value or it will have the random no and its not good

In [22]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [23]:
X_train = oe.transform(X_train)

In [24]:
X_train

array([[1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.]])

In [25]:
oe.categories_  # only to see

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [26]:
X_train

array([[1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.]])

In [28]:
from sklearn.preprocessing import LabelEncoder  # read the sklearn label encoder

In [32]:
le = LabelEncoder()

In [34]:
le.fit(Y_train)

LabelEncoder()

In [35]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [37]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [38]:
Y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1])