In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
import seaborn as sn
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [3]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [51]:
df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/test.csv')

In [52]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [53]:
df_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [54]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [55]:
df_test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [56]:
df_train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [57]:
df_test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [58]:
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].mean())

In [59]:
df_train.dropna(axis=0, how='any', subset='Embarked', inplace=True)
df_train.drop(df_train[['Cabin']],axis=1, inplace=True)

In [60]:
df_train.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [61]:
df_test.drop(df_test[['Cabin']],axis=1, inplace=True)

In [62]:
df_test.isna().sum()

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
Embarked        0
dtype: int64

In [63]:
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].mean())
df_test['Fare'] = df_test['Fare'].fillna(df_test['Fare'].mean())

In [64]:
df_train = df_train.drop(['Name', 'PassengerId', 'Ticket'], axis=1)

In [65]:
df_test = df_test.drop(['Name', 'PassengerId', 'Ticket'], axis=1)

In [66]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    object 
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 62.5+ KB


In [67]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      418 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [69]:
df_train = pd.get_dummies(df_train, columns=['Sex','Embarked'])

In [70]:
df_test = pd.get_dummies(df_test, columns=['Sex','Embarked'])

In [71]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Survived    889 non-null    int64  
 1   Pclass      889 non-null    int64  
 2   Age         889 non-null    float64
 3   SibSp       889 non-null    int64  
 4   Parch       889 non-null    int64  
 5   Fare        889 non-null    float64
 6   Sex_female  889 non-null    bool   
 7   Sex_male    889 non-null    bool   
 8   Embarked_C  889 non-null    bool   
 9   Embarked_Q  889 non-null    bool   
 10  Embarked_S  889 non-null    bool   
dtypes: bool(5), float64(2), int64(4)
memory usage: 53.0 KB


In [72]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      418 non-null    int64  
 1   Age         418 non-null    float64
 2   SibSp       418 non-null    int64  
 3   Parch       418 non-null    int64  
 4   Fare        418 non-null    float64
 5   Sex_female  418 non-null    bool   
 6   Sex_male    418 non-null    bool   
 7   Embarked_C  418 non-null    bool   
 8   Embarked_Q  418 non-null    bool   
 9   Embarked_S  418 non-null    bool   
dtypes: bool(5), float64(2), int64(3)
memory usage: 18.5 KB


In [74]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [76]:
df_train[['Age','Fare']] = scaler.fit_transform(df_train[['Age','Fare']])
df_train[['Age','Fare']]

Age      Fare
0   -0.590495 -0.500240
1    0.643971  0.788947
2   -0.281878 -0.486650
3    0.412509  0.422861
4    0.412509 -0.484133
..        ...       ...
886 -0.204724 -0.384475
887 -0.821957 -0.042213
888  0.003524 -0.174084
889 -0.281878 -0.042213
890  0.181046 -0.490173

[889 rows x 2 columns]

In [77]:
df_test[['Age','Fare']] = scaler.fit_transform(df_test[['Age','Fare']])
df_test[['Age','Fare']]

Age      Fare
0    0.334993 -0.498407
1    1.325530 -0.513274
2    2.514175 -0.465088
3   -0.259330 -0.483466
4   -0.655545 -0.418471
..        ...       ...
413  0.000000 -0.494448
414  0.691586  1.313753
415  0.651965 -0.508792
416  0.000000 -0.494448
417  0.000000 -0.237906

[418 rows x 2 columns]

In [83]:
X = df_train.iloc[:,1:]
y = df_train.iloc[:,0]

In [81]:
X.shape

(889, 10)

In [84]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 889, dtype: int64

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

In [86]:
lr.fit(X_train,y_train)

LogisticRegression()

In [87]:
lr.coef_
# fitted coef

array([[-1.00949516, -0.52546191, -0.31060105, -0.04886033,  0.10922687,
         1.33599733, -1.33489661,  0.19169261,  0.08866734, -0.27925923]])

In [88]:
lr.intercept_
# model intercept

array([2.41242859])

In [89]:
X_train.shape

(711, 10)

In [90]:
y_pred = lr.predict(X_test)

In [91]:
# accuracy
print('accuracy: ', accuracy_score(y_test,y_pred))

accuracy:  0.7752808988764045


In [92]:
confusion_matrix(y_test, y_pred)

array([[93, 16],
       [24, 45]], dtype=int64)

In [93]:
print('precision : ')
precision_score(y_test, y_pred)

precision : 


0.7377049180327869

In [94]:
print('recall : ')
recall_score(y_test, y_pred)

recall : 


0.6521739130434783

In [95]:
print('f1 score : ')
f1_score(y_test, y_pred)

f1 score : 


0.6923076923076923